### ISSUE TITLE
question

### ISSUE THREAD

**Issue by weallwegot** [dado3212/groupme-analysis#1]
where does the textual data from the groupme go/ is it stored anywhere? just curious i wanted to run this on a group im in but wanted to clarify what security was like.

Also, awesome project i was thinking of doing something really similar/identical, glad i looked around first!

**Comment by dado3212** [comment]
The raw textual data from the groupme is processed, and then discarded, it doesn't get stored anywhere.  However, the analysis IS stored, which includes top comments on a per-person basis.  Obviously, this data shouldn't be left unencrypted.  I use Sodium, with a 10 digit passcode generated with (openssl_random_pseudo_bytes(10)).  This passcode isn't stored, and is only available in the message that the bot sends in the groupme, passed in as a query parameter.

If the bot is removed from the group after processing, it doesn't have access to those messages.  And if you don't remove it, it can see all the messages anyways.  Therefore, if used properly, all the information about the group is left private.

That being said, if you still feel uncomfortable, you should be able to easily clone the repo, and adapt it into something that will run on your group without ever touching my server.  Enjoy!

**Comment by weallwegot** [comment]
ah okay, got it. thanks so much!
